name: deploy on main

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: setup cordova
        run: npm install -g cordova 

      - name: cordova create MyApp
        run: |
          cordova create MyApp
          cd MyApp
          cordova platform add android
          cordova build android --release

      - name: create keystore
        run: |
          cd MyApp
          keytool -genkey -v -keystore my-release-key.keystore -storepass myStorePassword -keyalg RSA -keysize 2048 -validity 10000 -alias my-key-alias -keypass myStorePassword -dname "CN=John Doe, OU=Dev Department, O=MyCompany, L=MyCity, ST=MyState, C=US" 

      - name: Build Android release APK
        run: |
          cd MyApp
          cordova build android --release -- --keystore=my-release-key.keystore --storePassword=myStorePassword --alias=my-key-alias --password=myStorePassword --packageType=apk

      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: android-app-release
          path: MyApp/platforms/android/app/build/outputs/apk/release/app-release.apk
